# Introduction {#intro}


## Disclaimer

This is a report of how I found it working on the Bernie campaign, mixed with opinions of mine about what happened. I went into 2020 as a Warren and Sanders fan, and so remain. I don't like the Democratic Party. I would rather them to the GOP, but I would rather an unpolished turd to the GOP. This piece is reflective of this point of view. I welcome comment from other points of view (though I rarely get that; friends and even family members are for the most part very unwilling to engage in political discussion here, for fear of I don't know what).


## How I ended up working for Bernie


### 2016

The Brexit referendum of 2016 frightened me. I desperately wanted Britain to remain in the EU. I voted and hoped other people wouldn't be _stupid_ and vote the other way. In other words, I did almost nothing other than feeling clever, followed by feeling disappointed. I had seen other people out campaigning for remain, but somehow I felt that that was a job for _those_ people. I still don't understand why. Maybe I didn't care as much as I said I did when I had a pint in my hand, or maybe I was just plain _stupid_. Anyway, I hate it that I did nothing.


### 2019

I met an American girl in England in 2015. I married her in 2018 and in 2019 I moved to Oakland, California with her. As Christmas approached, the Democratic Party primary was taking shape. I was particularly excited about Elizabeth Warren and Bernie Sanders. Paul Krugman explained this infatuation well in a January 2020 interview with Ezra Klein, saying "Something went wrong in the US to lead us to where we are now; only Bernie Sanders and Elizabeth Warren have a coherent theory of what that was." This is perhaps unfair on people like Andrew Yang (I cannot understand why he was never taken seriously but Mayor Pete was), but it captures the general idea. 

So yes, you could say I'm on the left. I want the government to provide healthcare without individual charges (call that _Medicare for all_ if you want to). I want taxes to be raised on people as lucky as myself (I'm an overpaid tech worker) or luckier to pay for things for people who don't have enough. I want to stop fossil fuel exploration. I want women and minorities to get equal pay for equal work. And so on.

Towards the end of 2019, Elizabeth Warren was rising in the polls. She almost caught Joe Biden; it was an exciting time. Being a frontrunner coming from the left, she faced an enormous amount of scrutiny. The New York Times, Washington Post, MSNBC, CNN and others pummeled her on the unaffordability of her _Medicare for All_ plan, which was originally just an endorsement of Sanders' plan. The pressure told. She wriggled around and came up with her own plan, slightly more _moderate_ than the original. Warren the flip flopper was kicked a few more times when she was down and that was the end of her. She had a notable moment left in her---roasting Mike Bloombberg alive on live TV---but she never had a shot again. 

Meanwhile Bernie Sanders had a heart attack and in a quite incredible feat of loyalty from his supporters, managed to brush it off and carry on with his campaign. He seemed to avoid the intense criticism on medicare for all that Warren sustained. You're allowed to believe in that if you're not going to win. 

In fall (that's autumn for you Europeans) of 2019, I had tried a few times to get involved in the Warren campaign, but they were slow in getting back to me; they didn't really seem to be up and running in California. When I tried to get involved with the Bernie campaign in early 2020, it was quickly evident that this was already a well-oiled machine in my locality. In I went.


# 2020

I'm in, I'm working for Bernie (call me a bro if it makes you feel good). My day job  at the time was contract work at Facebook, so I was villain by day, hero at night (at least in my own head). The work at Facebook was so fantastically undemanding that I had a lot of time and energy to devote to Bernie work. I never did Bernie stuff at work, but I could often leave early. The Oakland campaign office was on my block and I was in there more nights than not in the month before Super Tuesday (which includes the California primary). 
