# Bernie supporters


## Different demographics with different concerns

I met lots of wonderful Bernie supporters on the campaign. Most people had one particular issue that they cared about. I think it's interesting for a moment to dwell on who cared about what (of course I'll have to generalise and in reality these groups overlap and I only met a handful of people from these groups). 

There were a lot of teachers and nurses, who cared about schools and healthcare. They also cared about their own wages, as they should; their wages under-value their work. These people were lifelong union members, many of them union organisers. Bernie often mentioned teachers and nurses in his stump speeches and teachers and nurses seemed to feel that Bernie really loved and valued them like no other candidate. Being teachers and nurses, the vast majority were women.

There were a hell of a lot of young people. They fear climate change and environmental destruction. I'll put myself into that category. They are also very worried about being able to afford a house; if I had aspirations of owning a home near the San Francisco Bay Area, I'd be worried about that too. As far as I could tell, all of the young people campaigning for Bernie were university educated. I was a bit disappointed by this. It would've been more interesting to have a mix and strategically, this didn't bode well for us. Curiously, many of these young people had never voted before (even though they had been of voting age in previous elections), mostly because they hadn't had a candidate that was far left enough to turn them out. I thought this did bode well for us; turning out new voters was key to the strategy.

There were a lot of old people (ages 60 and above). They were very angry about American foreign policy. Iraq was the last straw for them. The Obama administration's continued support for Saudi Arabia in their war with Yemen was last plus one. For most of them, their bitterness started with the Vietnam war. The no longer trusted what their government or mainstream media or government tell them about foreign policy. For them, Iraq was confirmation of what they already knew. They absolutely hated anyone who voted for that war, Joe Biden and Hillary Clinton being the most notable. These people also hated the US mainstream media. I remember one gentleman recalling that only the _Long Island Newsday_ had reported on the US invasion of Panama in 1989. Back then he was still very bitter about Vietnam (he hadn't fought there but he was part of the anti-war protest movement at the time). This media blackout of the Panama invasion in '89 confirmed to him that the US media had not learned to hold the US government to account. He now reads _The Guardian_ to get his US news!

The black people that I met were most worried about police brutality against them and the disproportionate number of black people in prison. They hated Mike Bloomberg for _stop and frisk_. I was surprised that the black people I met never raised other issues of systemic racism, for example the pay gap. For them, the immediate threat was police violence; all else was secondary. Chief among secondary concerns was the price of housing. There was a lesson for me there. I feel like I learned a lot more by talking to a few dozen ordinary people than by reading a thousand articles. Before George Floyd's murder, for every article I came across discussing police violence against black people, there were ten that were designed to subtly inform me that I myself am probably subconsciously racist and should be aware of that (and I read them all like a fool). The news should be flooded with stories of unnecessary violence against people of colour and the moral imperative to stop it. We've had a decade of this unconscious bias stuff now. Sure, unconscious biases exist. But the solutions for the people on the ground exist right now and could be implemented right now. Many were in Bernie's policies. If we're to de-unconscious bias our way out of this, it'll take several generations. To wait that long is unconscionable.





