# The work


## Canvassing

The most important thing one did on the campaign was canvassing: knocking on doors and talking to people about why Bernie might be right for them. I live in downtown Oakland and there was a high density of volunteers here, so on the weekend we would carpool to places with relatively few volunteers (mostly less-affluent suburbs of Oakland). This was my favourite thing to do, because it really got me out of my bubble (the overpaid tech worker bubble). I'll share some stories later to illustrate why this was so enjoyable. 

The canvassing training was very good (I thought). We were told to do as much listening as possible at the door. Let people tell you what they care about and then try to explain why a Bernie presidency aligned with their goals. One needed only a broad overview of Bernie's policy to be competent at the doors. Very few people were interested in the minutiae of the policies, and if they were, you weren't going to change their mind with a two-minute conversation. Most people would mention the price of rent or the fact that they'd once lost their healthcare when they lost their job (this has happened to a terrible number of people) and so a short explanation of Bernie's public housing or _Medicare for all_ plans sufficed. Really, you were trying to impart to people that you gave a damn about their struggles, that you wanted them to be helped out. 

You never wanted to be in the position of vomitting policies at people. This basically never worked. You always wanted them to be telling you what mattered to them. A common technique was to tell a story of something that had impacted you in the past. My go to was that when I came to the US, being unemployed at first I enrolled in Medicare but I could never get confirmation that I was actually covered. After a couple of months I got a job and bought private insurance. I never really found out when my Medicare coverage began, although I know that at some stage it did. This very boring story actually resonated with a lot of people because so many had had a similar experience. If after telling such a story, you still couldn't trigger people to start talking after the personal story, you were in trouble. At this point, you had no hope other than to tell them about your favorite policies in the hope that one of them would light their eyes up. This never happened.

Most people didn't answer the door. In most of these cases, there probably wasn't anyone home, but sometimes there clearly was. I didn't mind people not answering the door, that's up them. However, in future when people knock on mine, I will definitely answer, knowing the feeling of knocking a dozen doors in a row with no answer. When people did answer, it was almost always a pleasant experience. People could sometimes be nasty over the phone, but almost never in person.

The response to Bernie as a candidate was overwhelmingly positive. Even people who were going to vote for someone else seemed to like Bernie. There was an obvious generational divide. Young people loved Bernie (it still amazes me thinking about the level of enthusiasm that young voters had for this very old man). Middle aged people were on the fence about him, leaning towards Mayor Pete (incidentally I really dislike Mayor Pete because he doesn't seem to stand for anything in particular) for the most part. Older people liked Biden. In particular, older black people really respected Biden for being Obama's VP. They liked Bernie but were firmly with Joe. It was nice to hear these people say how much it meant to their community to see a black man in the White House. There was also an interesting divide among women. Almost all white women that I spoke to were for Warren, whereas black, Asian and latina women were all about Bernie. I tried to convince these white women that Warren was toast (she was at this stage) and that therefore they should go to Bernie, and told them that I myself had switched from the Warren campaign for this reason (this was a small lie: I _signed up_ to be a Warren volunteer twice and they never got back to me and a few weeks later I joined the Bernie campaign). This never worked. There were definitely a lot of women out there who desperately wanted a woman president and were voting accordingly; this is not something that I surmised, the women told me this themselves. I always made sure to ask these women "Why not Klobuchar" and they always said it wasn't close between Warren and Klobuchar. I never met a Klobuchar supporter. It was always cordial when I met a Warren supporter, there was often a sense that we were on the same team. I never met a Warren supporter than I didn't like.

The best chance you had at convincing people to vote for your candidate i.e. gaining a vote was in encounters with habitual voters who were not politically engaged. There were a lot of these people out there: people who believed forcefully in the importance of casting a vote, but seemed relatively unconcerned with who they might end up voting _for_. As I alluded to above, the key with these people was to try to stay friendly while figuring out what they cared about. If you could do that, it was inevitable that you could explain how Bernie planned to address that issue of theirs. This was something that you got better at with practice. The first few doors you knock, you're a babbling mess but before long you get comfortable with what works for you. Mostly, people who answer their door in the first place are friendly. Sometimes they're too busy to talk to you and they tell you so, so you walk away without protest. Still, that person has now had a polite interaction with a Bernie representative. It counts for something. 

The other kind of vote gaining that you could do was to find people who already favoured Bernie and simply remind them about when and how to vote. It was amazing how many people didn't know how to go about voting. For example, people who registered as having no party preference would not be able by default to vote in the democratic primary but they could request a ballot with which to do so. Helping people with this amounted to a lot of votes. On polling day, I was out canvassing and reminding people to vote right up until voting closed. As voting closed, just for the hell of it I tried to find the local polling station. It was there aright but it was in a small room at the back of a labyrinthine community centre and assisted living facility. There were no signposts and a lot of people wandering around wondering where exactly to vote. Every so often people who had already found where to go would emerge and send a new flock towards the polling station. There were also a lot of people arriving there right at the deadline. If you were in the line at the time of the deadline, you could vote. Some did arrive too late. Having spend the last two hours wandering around in the cold and dark entreating people to go and vote before the deadline came near, that was a bitter pill to swallow. 

I must mention the pain of canvassing people who are politically disengaged. Once someone has told you they have "no interest" in voting, there is nothing you can do. You are a self-identified political operative and as such they tune you out. You go through what you were trained to do. "Do you like other people making decisions for you?" It is hopeless. I liked may of the disinterested non-voters that I encountered. They were polite enough to stand there and pretend to listen to my routine, and when it was over, they gave a polite goodbye. A key part of the campaign strategy was to turn out this type of person. "Turn out people who never voted before!" In the abstract, it made sense. Bernie was an unconventional candidate and as such he probably needed to plot an unconventional path to victory. In the moment though, this strategy was soul destroying. This kind of interaction was far more common in poor neighborhoods, who needed Bernie the most. On the other hand, though, who am I to tell people like this what they need? 

I don't want to be too fatalistic about what I am saying here. I think appeals to non-voters should be happening in any functioning democracy. But voting is a cultural thing: it's something that people tend to do if their friends and family also do so. To change non-voters into voters, we need to change the culture around non-voters. This is a difficult and lengthy process, but attempts can be made. For example, people with a university education are more likely to vote. Removing barriers of entry into university education would surely then be a good attempt at increasing voter turnout. (Of course this has the undesired effect of biasing the electorate further towards the university educated, which is a huge caveat.)


## Phone banking

Phone banking is just calling people. There were two types of phone banking: calling voters and calling volunteers. 

For calling voters, there was an online portal called the "Bernie Dialer." At any given time it would connect you with voters in key strategic parts of the country (usually a state with an upcoming primary). It was interesting to note how different it was to call different parts of the country. If Bernie was popular in that state, it was a nice experience and if not it was rough. California, Washington, Nevada and Texas were nice to call (yes Bernie was surprisingly popular in Texas). Florida was particularly horrible. When people feel like you've bothered them at home to promote someone that they've made up their mind is bad, they often make sure to get an insult in as they hang up the phone. On the whole though, my experiences talking to American strangers were positive. I'll share some specific stories later.

Calling volunteers was mostly about turning people out to canvas. For example, if there was a canvas scheduled in San Lorenzo on a given Saturday, someone like me would obtain a list of people who had in the past signed up as Bernie volunteers and lived local to the canvas area, and call every one of them and ask them to show up. This was always a much more pleasant experience, because everyone you called was a Bernie supporter. 
