# What Now

## Trust Bernie and keep pushing

Bernie has endorsed Joe Biden and together their joint policy task forces have come up with some quite exciting plans on climate and the environment, which are issues dear to my heart. On other issues e.g. healthcare (Biden's _public option_ is a very long way from an unconditional guarantee of healthcare to all) and criminal justice reform (I'm not an _abolish the police_ guy, but I do believe that there are a ridiculous number of people in prison here and that cash bail is wrong). Bernie's endorsement of Biden means that he thinks life will be better for the worse off if Trump is defeated. I trust him on that and the idea that "they've reeled Bernie into the establishment" is hysterical. 

Broadly speaking I am _on the left_ and what I consider to be _the left_ is still in the minority in this country. My vision for how the left gains power and influence is through democratic means. We came close to getting Bernie elected by those means and I think that's a realistic path to success for us in future. Trump and his goons have no qualms about destroying these democratic means by which we might succeed. They would happily block every minority from voting if they could. Then what are we going to do? Of course it doesn't feel good to be supporting Biden right now, but I think those of us on the left need to be very clear-eyed about how we chart the path to where we want to be. I honestly think the best thing for us to do is to help Biden win and then primary challenge him in four years (if he's even running again). There is no hypocrisy in that, no selling out. 


## Congress

There are congressional races there to be won. Recently, in NY 16th congressional district, Jamaal Bowman unseated 30-year incumbent Eliot Engel, chair of the foreign affairs committee. Bowman was backed by left groups like the Sunrise Movement, The Jewish Vote and Justice Democrats. About 75,000 votes were cast in that election. Bowman's campaign made over 1,200,000 phone calls, more than 2/3 of which were made by the Sunrise Movement alone. Engel was backed by pretty much the whole democratic establishment including Nancy Pelosi, Chuck Shumer, Hillary Clinton, the Congressional Black Caucus and numerous corporate PACs. Bowman, like Bernie, didn't take money from corporate PACs. It was cool to see him cross the line having thrown some money his way myself, especially having done the same with Bernie. 

There are other similar victories throughout the country e.g. Candace Valenzuela, Mondaire Jones and Mike Siegel. There are also notable defeats e.g. Andrew Romanoff; indeed we still lose more often than we win. But through force of numbers and conviction, the left is beginning to wield power that up until recently it simply didn't have.


# More on Biden

I get the idea of the left refusing to back a _moderate_ candidate against a right-wing candidate and I think it has its merits _if_ it's part of a plausible longer term strategy for the left to elect people more sympathetic to its cause. In this case, Trump is hell bent on destroying the very democratic means that the left might hope to use to succeed in future. Although Biden is not overly sympathetic to the left, I do think he believes in the democratic process. Also given the obvious fact that the upcoming election will be won by either Biden or Trump, I think it's in the lefts short and long term best interest to make sure Biden wins, even if it's not a great best.